// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RepositoryEf.Data.Models;

public partial class Factura
{
    public int FacturaId { get; set; }

    public DateTime Fecha { get; set; }

    public int FormaPagoId { get; set; }

    public string Cliente { get; set; }

    public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; } = new List<DetalleFactura>();

    public virtual FormaPago FormaPago { get; set; }
}