// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace RepositoryEf.Data.Models;

public partial class FactDbContext : DbContext
{
    public FactDbContext(DbContextOptions<FactDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Articulo> Articulos { get; set; }

    public virtual DbSet<DetalleFactura> DetalleFacturas { get; set; }

    public virtual DbSet<Factura> Facturas { get; set; }

    public virtual DbSet<FormaPago> FormaPagos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Articulo>(entity =>
        {
            entity.HasKey(e => e.ArticuloId).HasName("PK__Articulo__C0D725ED79C60D72");

            entity.ToTable("Articulo");

            entity.HasIndex(e => e.Nombre, "IX_Articulo_Nombre");

            entity.HasIndex(e => e.Nombre, "UQ_Articulo_Nombre").IsUnique();

            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.PrecioUnitario).HasColumnType("decimal(18, 4)");
        });

        modelBuilder.Entity<DetalleFactura>(entity =>
        {
            entity.HasKey(e => e.DetalleId).HasName("PK__DetalleF__6E19D6DAC53B8C36");

            entity.ToTable("DetalleFactura");

            entity.HasIndex(e => e.FacturaId, "IX_DetalleFactura_FacturaId");

            entity.HasIndex(e => new { e.FacturaId, e.ArticuloId }, "UQ_Detalle_Factura_Articulo").IsUnique();

            entity.Property(e => e.PrecioUnitario).HasColumnType("decimal(18, 4)");

            entity.HasOne(d => d.Articulo).WithMany(p => p.DetalleFacturas)
                .HasForeignKey(d => d.ArticuloId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Detalle_Articulo");

            entity.HasOne(d => d.Factura).WithMany(p => p.DetalleFacturas)
                .HasForeignKey(d => d.FacturaId)
                .HasConstraintName("FK_Detalle_Factura");
        });

        modelBuilder.Entity<Factura>(entity =>
        {
            entity.HasKey(e => e.FacturaId).HasName("PK__Factura__5C024865E6967C07");

            entity.ToTable("Factura");

            entity.Property(e => e.Cliente).HasMaxLength(250);
            entity.Property(e => e.Fecha)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.FormaPago).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.FormaPagoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Factura_FormaPago");
        });

        modelBuilder.Entity<FormaPago>(entity =>
        {
            entity.HasKey(e => e.FormaPagoId).HasName("PK__FormaPag__920B09FE71C2244C");

            entity.ToTable("FormaPago");

            entity.HasIndex(e => e.Nombre, "UQ__FormaPag__75E3EFCF2558B0B7").IsUnique();

            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}